o = Organization.create(name: 'Team')
annotator = Annotator.create(username: 'test', screenname: 'テスト', password: '123456', organization: o)
Annotator.create(username: 'admin', screenname: 'admin', password: '123456', admin: true, organization: o)
30.times do |n|
  Annotator.create!(username: "user#{n}", screenname: "ユーザー#{n}", password: '123456', organization: o)
end

category = Category.create!(name: 'continental_region', screenname: '大陸地域名', def_link: 'http://example.com')

# load attributes
# ---------------

AnnotationAttribute.create!(name: 'kana', screenname: 'ふりがな', category: category)
AnnotationAttribute.create!(name: 'alias', screenname: '別名', category: category)
AnnotationAttribute.create!(name: 'location', screenname: '所在地', category: category)
AnnotationAttribute.create!(name: 'member_country', screenname: '構成国', category: category)
AnnotationAttribute.create!(name: 'constituent_region', screenname: '構成地域', category: category)
AnnotationAttribute.create!(name: 'major_city', screenname: '主要都市', category: category)
AnnotationAttribute.create!(name: 'established_time', screenname: '成立時期', category: category)
AnnotationAttribute.create!(name: 'population', screenname: '人口', category: category)
AnnotationAttribute.create!(name: 'year_of_population_data', screenname: '人口データの年', category: category)
AnnotationAttribute.create!(name: 'population_density', screenname: '人口密度', category: category)
AnnotationAttribute.create!(name: 'area', screenname: '面積', category: category)
AnnotationAttribute.create!(name: 'ethnic_group', screenname: '民族', category: category)
AnnotationAttribute.create!(name: 'language', screenname: '言語', category: category)
AnnotationAttribute.create!(name: 'origin_of_name', screenname: '地名の由来', category: category)
AnnotationAttribute.create!(name: 'war', screenname: '戦争', category: category)

category = Category.create!(name: 'country', screenname: '国名', def_link: 'http://example.com')

# load attributes
# ---------------

AnnotationAttribute.create!(name: 'kana', screenname: 'ふりがな', category: category)
AnnotationAttribute.create!(name: 'alias', screenname: '別名', category: category)
AnnotationAttribute.create!(name: 'formal_name', screenname: '正式名称', category: category)
AnnotationAttribute.create!(name: 'current_place_name', screenname: '現在の地名', category: category)
AnnotationAttribute.create!(name: 'location', screenname: '所在地', category: category)
AnnotationAttribute.create!(name: 'major_city', screenname: '主要都市', category: category)
AnnotationAttribute.create!(name: 'capital', screenname: '首都', category: category)
AnnotationAttribute.create!(name: 'neighboring_country', screenname: '隣国', category: category)
AnnotationAttribute.create!(name: 'sovereign_state', screenname: '主権国家', category: category)
AnnotationAttribute.create!(name: 'establishment_year', screenname: '成立年', category: category)
AnnotationAttribute.create!(name: 'annihilation_year', screenname: '消滅年', category: category)
AnnotationAttribute.create!(name: 'population', screenname: '人口', category: category)
AnnotationAttribute.create!(name: 'year_of_population_data', screenname: '人口データの年', category: category)
AnnotationAttribute.create!(name: 'population_density', screenname: '人口密度', category: category)
AnnotationAttribute.create!(name: 'area', screenname: '面積', category: category)
AnnotationAttribute.create!(name: 'currency', screenname: '通貨', category: category)
AnnotationAttribute.create!(name: 'official_language', screenname: '公用語', category: category)
AnnotationAttribute.create!(name: 'religion', screenname: '宗教', category: category)
AnnotationAttribute.create!(name: 'famous_facility', screenname: '著名施設', category: category)
AnnotationAttribute.create!(name: 'famous_terrain', screenname: '著名な地形', category: category)
AnnotationAttribute.create!(name: 'origin_of_name', screenname: '国名の由来', category: category)
AnnotationAttribute.create!(name: 'war', screenname: '戦争', category: category)
AnnotationAttribute.create!(name: 'treaty', screenname: '条約', category: category)

category = Category.create!(name: 'county', screenname: '郡名', def_link: 'http://example.com')

# load attributes
# ---------------

AnnotationAttribute.create!(name: 'kana', screenname: 'ふりがな', category: category)
AnnotationAttribute.create!(name: 'alias', screenname: '別名', category: category)
AnnotationAttribute.create!(name: 'type', screenname: '種類', category: category)
AnnotationAttribute.create!(name: 'country', screenname: '国', category: category)
AnnotationAttribute.create!(name: 'domestic_position', screenname: '国内位置', category: category)
AnnotationAttribute.create!(name: 'location', screenname: '所在地', category: category)
AnnotationAttribute.create!(name: 'merged_area', screenname: '合併区域', category: category)
AnnotationAttribute.create!(name: 'county_seat', screenname: '郡庁所在地', category: category)
AnnotationAttribute.create!(name: 'establishment_year', screenname: '成立年', category: category)
AnnotationAttribute.create!(name: 'annihilation_year', screenname: '消滅年', category: category)
AnnotationAttribute.create!(name: 'population', screenname: '人口', category: category)
AnnotationAttribute.create!(name: 'year_of_population_data', screenname: '人口データの年', category: category)
AnnotationAttribute.create!(name: 'population_density', screenname: '人口密度', category: category)
AnnotationAttribute.create!(name: 'area', screenname: '面積', category: category)
AnnotationAttribute.create!(name: 'head', screenname: '首長', category: category)
AnnotationAttribute.create!(name: 'famous_facility', screenname: '著名施設', category: category)
AnnotationAttribute.create!(name: 'tourist_spot', screenname: '観光地', category: category)
AnnotationAttribute.create!(name: 'origin_of_name', screenname: '地名の由来', category: category)
AnnotationAttribute.create!(name: 'sister_city', screenname: '友好自治体', category: category)

category = Category.create!(name: 'domestic_region', screenname: '国内地域名', def_link: 'http://example.com')

# load attributes
# ---------------

AnnotationAttribute.create!(name: 'kana', screenname: 'ふりがな', category: category)
AnnotationAttribute.create!(name: 'alias', screenname: '別名', category: category)
AnnotationAttribute.create!(name: 'country', screenname: '国', category: category)
AnnotationAttribute.create!(name: 'domestic_position', screenname: '国内位置', category: category)
AnnotationAttribute.create!(name: 'location', screenname: '所在地', category: category)
AnnotationAttribute.create!(name: 'constituent_municipality', screenname: '構成自治体', category: category)
AnnotationAttribute.create!(name: 'population', screenname: '人口', category: category)
AnnotationAttribute.create!(name: 'year_of_population_data', screenname: '人口データの年', category: category)
AnnotationAttribute.create!(name: 'population_density', screenname: '人口密度', category: category)
AnnotationAttribute.create!(name: 'area', screenname: '面積', category: category)
AnnotationAttribute.create!(name: 'famous_terrain', screenname: '著名な地形', category: category)
AnnotationAttribute.create!(name: 'industry', screenname: '産業', category: category)
AnnotationAttribute.create!(name: 'origin_of_name', screenname: '地名の由来', category: category)

category = Category.create!(name: 'gpe_other', screenname: 'ＧＰＥ_その他', def_link: 'http://example.com')

# load attributes
# ---------------

AnnotationAttribute.create!(name: 'kana', screenname: 'ふりがな', category: category)
AnnotationAttribute.create!(name: 'alias', screenname: '別名', category: category)
AnnotationAttribute.create!(name: 'type', screenname: '種類', category: category)
AnnotationAttribute.create!(name: 'location', screenname: '所在地', category: category)
AnnotationAttribute.create!(name: 'major_city', screenname: '主要都市', category: category)
AnnotationAttribute.create!(name: 'governing_nation', screenname: '統治国家', category: category)
AnnotationAttribute.create!(name: 'establishment_year', screenname: '成立年', category: category)
AnnotationAttribute.create!(name: 'annihilation_year', screenname: '消滅年', category: category)
AnnotationAttribute.create!(name: 'population', screenname: '人口', category: category)
AnnotationAttribute.create!(name: 'year_of_population_data', screenname: '人口データの年', category: category)
AnnotationAttribute.create!(name: 'population_density', screenname: '人口密度', category: category)
AnnotationAttribute.create!(name: 'area', screenname: '面積', category: category)
AnnotationAttribute.create!(name: 'ethnic_group', screenname: '民族', category: category)
AnnotationAttribute.create!(name: 'official_language', screenname: '公用語', category: category)
AnnotationAttribute.create!(name: 'other_language', screenname: '公用語以外の言語', category: category)
AnnotationAttribute.create!(name: 'latitude', screenname: '座標・緯度', category: category)
AnnotationAttribute.create!(name: 'longitude', screenname: '座標・経度', category: category)
AnnotationAttribute.create!(name: 'origin_of_name', screenname: '地名の由来', category: category)

category = Category.create!(name: 'province', screenname: '都道府県州名', def_link: 'http://example.com')

# load attributes
# ---------------

AnnotationAttribute.create!(name: 'kana', screenname: 'ふりがな', category: category)
AnnotationAttribute.create!(name: 'alias', screenname: '別名', category: category)
AnnotationAttribute.create!(name: 'type', screenname: '種類', category: category)
AnnotationAttribute.create!(name: 'country', screenname: '国', category: category)
AnnotationAttribute.create!(name: 'domestic_position', screenname: '国内位置', category: category)
AnnotationAttribute.create!(name: 'location', screenname: '所在地', category: category)
AnnotationAttribute.create!(name: 'merged_prefecture_or_state', screenname: '合併都道府県州', category: category)
AnnotationAttribute.create!(name: 'major_city', screenname: '主要都市', category: category)
AnnotationAttribute.create!(name: 'capital', screenname: '州都・県庁所在地', category: category)
AnnotationAttribute.create!(name: 'neighboring_country', screenname: '接する国', category: category)
AnnotationAttribute.create!(name: 'neighboring_county', screenname: '隣州・県', category: category)
AnnotationAttribute.create!(name: 'establishment_year', screenname: '成立年', category: category)
AnnotationAttribute.create!(name: 'population', screenname: '人口', category: category)
AnnotationAttribute.create!(name: 'year_of_population_data', screenname: '人口データの年', category: category)
AnnotationAttribute.create!(name: 'population_density', screenname: '人口密度', category: category)
AnnotationAttribute.create!(name: 'area', screenname: '面積', category: category)
AnnotationAttribute.create!(name: 'latitude', screenname: '座標・緯度', category: category)
AnnotationAttribute.create!(name: 'longitude', screenname: '座標・経度', category: category)
AnnotationAttribute.create!(name: 'head', screenname: '首長', category: category)
AnnotationAttribute.create!(name: 'famous_facility', screenname: '著名施設', category: category)
AnnotationAttribute.create!(name: 'famous_terrain', screenname: '著名な地形', category: category)
AnnotationAttribute.create!(name: 'tourist_spot', screenname: '観光地', category: category)
AnnotationAttribute.create!(name: 'regular_event', screenname: '恒例行事', category: category)
AnnotationAttribute.create!(name: 'specialty_good', screenname: '特産品', category: category)
AnnotationAttribute.create!(name: 'industry', screenname: '産業', category: category)
AnnotationAttribute.create!(name: 'origin_of_name', screenname: '地名の由来', category: category)


category = Category.create!(name: 'bay', screenname: '湾名', def_link: 'http://example.com')

# load attributes
# ---------------

AnnotationAttribute.create!(name: 'kana', screenname: 'ふりがな', category: category)
AnnotationAttribute.create!(name: 'alias', screenname: '別名', category: category)
AnnotationAttribute.create!(name: 'country', screenname: '国', category: category)
AnnotationAttribute.create!(name: 'domestic_position', screenname: '国内位置', category: category)
AnnotationAttribute.create!(name: 'location', screenname: '所在地', category: category)
AnnotationAttribute.create!(name: 'belonging_sea_area', screenname: '属する海域', category: category)
AnnotationAttribute.create!(name: 'belonging_bay', screenname: '属する湾', category: category)
AnnotationAttribute.create!(name: 'constituent_bay', screenname: '構成する湾', category: category)
AnnotationAttribute.create!(name: 'river', screenname: '河川', category: category)
AnnotationAttribute.create!(name: 'island', screenname: '島', category: category)
AnnotationAttribute.create!(name: 'formation_time', screenname: '形成時期', category: category)
AnnotationAttribute.create!(name: 'freezing_time', screenname: '氷結時期', category: category)
AnnotationAttribute.create!(name: 'water_depth', screenname: '水深', category: category)
AnnotationAttribute.create!(name: 'average_depth', screenname: '平均水深', category: category)
AnnotationAttribute.create!(name: 'maximum_depth', screenname: '最大水深', category: category)
AnnotationAttribute.create!(name: 'area', screenname: '面積', category: category)
AnnotationAttribute.create!(name: 'length', screenname: '長さ', category: category)
AnnotationAttribute.create!(name: 'width', screenname: '幅', category: category)
AnnotationAttribute.create!(name: 'width_of_mouth', screenname: '湾口幅', category: category)
AnnotationAttribute.create!(name: 'length_of_coastline', screenname: '海岸線の長さ', category: category)
AnnotationAttribute.create!(name: 'latitude', screenname: '座標・緯度', category: category)
AnnotationAttribute.create!(name: 'longitude', screenname: '座標・経度', category: category)
AnnotationAttribute.create!(name: 'tourist_spot', screenname: '観光地', category: category)
AnnotationAttribute.create!(name: 'harbor', screenname: '港', category: category)
AnnotationAttribute.create!(name: 'bridge_tunnel', screenname: '橋・トンネル', category: category)
AnnotationAttribute.create!(name: 'park', screenname: '公園', category: category)
AnnotationAttribute.create!(name: 'animal', screenname: '動物', category: category)
AnnotationAttribute.create!(name: 'origin_of_name', screenname: '名前の謂れ', category: category)

category = Category.create!(name: 'geological_region_other', screenname: '地形名_その他', def_link: 'http://example.com')

# load attributes
# ---------------

AnnotationAttribute.create!(name: 'alias', screenname: '別名', category: category)
AnnotationAttribute.create!(name: 'kana', screenname: 'ふりがな', category: category)
AnnotationAttribute.create!(name: 'country', screenname: '国', category: category)
AnnotationAttribute.create!(name: 'domestic_position', screenname: '国内位置', category: category)
AnnotationAttribute.create!(name: 'location', screenname: '所在地', category: category)
AnnotationAttribute.create!(name: 'type', screenname: '種類', category: category)
AnnotationAttribute.create!(name: 'area', screenname: '面積', category: category)
AnnotationAttribute.create!(name: 'length', screenname: '長さ', category: category)
AnnotationAttribute.create!(name: 'width', screenname: '幅', category: category)
AnnotationAttribute.create!(name: 'height', screenname: '高さ', category: category)
AnnotationAttribute.create!(name: 'water_depth', screenname: '水深', category: category)
AnnotationAttribute.create!(name: 'origin_of_name', screenname: '名前の謂れ', category: category)
AnnotationAttribute.create!(name: 'terrain', screenname: '構成する地形', category: category)
AnnotationAttribute.create!(name: 'selected_title', screenname: '選定されたタイトル', category: category)
AnnotationAttribute.create!(name: 'year_of_title_selection', screenname: 'タイトル選定の年', category: category)
AnnotationAttribute.create!(name: 'animal', screenname: '動物', category: category)
AnnotationAttribute.create!(name: 'plant', screenname: '植物', category: category)
AnnotationAttribute.create!(name: 'latitude', screenname: '座標・緯度', category: category)
AnnotationAttribute.create!(name: 'longitude', screenname: '座標・経度', category: category)

category = Category.create!(name: 'island', screenname: '島名', def_link: 'http://example.com')

# load attributes
# ---------------

AnnotationAttribute.create!(name: 'kana', screenname: 'ふりがな', category: category)
AnnotationAttribute.create!(name: 'alias', screenname: '別名', category: category)
AnnotationAttribute.create!(name: 'type', screenname: '種類', category: category)
AnnotationAttribute.create!(name: 'country', screenname: '国', category: category)
AnnotationAttribute.create!(name: 'domestic_position', screenname: '国内位置', category: category)
AnnotationAttribute.create!(name: 'location', screenname: '所在地', category: category)
AnnotationAttribute.create!(name: 'major_city', screenname: '主要都市', category: category)
AnnotationAttribute.create!(name: 'ocean', screenname: '海洋', category: category)
AnnotationAttribute.create!(name: 'position_in_ocean', screenname: '海洋内位置', category: category)
AnnotationAttribute.create!(name: 'bay', screenname: '湾', category: category)
AnnotationAttribute.create!(name: 'position_in_bay', screenname: '湾内位置', category: category)
AnnotationAttribute.create!(name: 'belonging_islands', screenname: '属する諸島', category: category)
AnnotationAttribute.create!(name: 'position_in_islands', screenname: '諸島内の位置', category: category)
AnnotationAttribute.create!(name: 'constituent_island', screenname: '構成する島', category: category)
AnnotationAttribute.create!(name: 'highest_peak', screenname: '最高峰', category: category)
AnnotationAttribute.create!(name: 'nearby_terrain', screenname: '付近の大陸・地形', category: category)
AnnotationAttribute.create!(name: 'latitude', screenname: '座標・緯度', category: category)
AnnotationAttribute.create!(name: 'longitude', screenname: '座標・経度', category: category)
AnnotationAttribute.create!(name: 'area', screenname: '面積', category: category)
AnnotationAttribute.create!(name: 'length', screenname: '長さ', category: category)
AnnotationAttribute.create!(name: 'width', screenname: '幅', category: category)
AnnotationAttribute.create!(name: 'circumference', screenname: '周囲', category: category)
AnnotationAttribute.create!(name: 'highest_point', screenname: '最高地点の高さ', category: category)
AnnotationAttribute.create!(name: 'number_of_islands', screenname: '島数', category: category)
AnnotationAttribute.create!(name: 'population', screenname: '人口', category: category)
AnnotationAttribute.create!(name: 'year_of_population_data', screenname: '人口データの年', category: category)
AnnotationAttribute.create!(name: 'rock_composition', screenname: '含有岩石', category: category)
AnnotationAttribute.create!(name: 'animal', screenname: '動物', category: category)
AnnotationAttribute.create!(name: 'plant', screenname: '植物', category: category)
AnnotationAttribute.create!(name: 'terrain', screenname: '地形', category: category)
AnnotationAttribute.create!(name: 'facility', screenname: '施設', category: category)
AnnotationAttribute.create!(name: 'tourist_spot', screenname: '観光地', category: category)
AnnotationAttribute.create!(name: 'bridge_tunnel', screenname: '橋・トンネル', category: category)
AnnotationAttribute.create!(name: 'industry', screenname: '産業', category: category)
AnnotationAttribute.create!(name: 'origin_of_name', screenname: '名前の謂れ', category: category)

category = Category.create!(name: 'lake', screenname: '湖沼名', def_link: 'http://example.com')

# load attributes
# ---------------

AnnotationAttribute.create!(name: 'kana', screenname: 'ふりがな', category: category)
AnnotationAttribute.create!(name: 'alias', screenname: '別名', category: category)
AnnotationAttribute.create!(name: 'type', screenname: '種類', category: category)
AnnotationAttribute.create!(name: 'country', screenname: '国', category: category)
AnnotationAttribute.create!(name: 'domestic_position', screenname: '国内位置', category: category)
AnnotationAttribute.create!(name: 'location', screenname: '所在地', category: category)
AnnotationAttribute.create!(name: 'shore_regionalization', screenname: '湖岸の地域区分', category: category)
AnnotationAttribute.create!(name: 'constituent_lake', screenname: '構成する湖沼', category: category)
AnnotationAttribute.create!(name: 'inflow_outflow_river', screenname: '流入・流出河川', category: category)
AnnotationAttribute.create!(name: 'island', screenname: '島', category: category)
AnnotationAttribute.create!(name: 'formation_time', screenname: '形成時期', category: category)
AnnotationAttribute.create!(name: 'water_depth', screenname: '水深', category: category)
AnnotationAttribute.create!(name: 'average_depth', screenname: '平均水深', category: category)
AnnotationAttribute.create!(name: 'maximum_depth', screenname: '最大水深', category: category)
AnnotationAttribute.create!(name: 'area', screenname: '面積', category: category)
AnnotationAttribute.create!(name: 'length', screenname: '長さ', category: category)
AnnotationAttribute.create!(name: 'width', screenname: '幅', category: category)
AnnotationAttribute.create!(name: 'circumference', screenname: '周囲長', category: category)
AnnotationAttribute.create!(name: 'water_volume', screenname: '貯水量', category: category)
AnnotationAttribute.create!(name: 'surface_elevation', screenname: '水面標高', category: category)
AnnotationAttribute.create!(name: 'transparency', screenname: '透明度', category: category)
AnnotationAttribute.create!(name: 'water_quality', screenname: '水質（淡水・汽水）', category: category)
AnnotationAttribute.create!(name: 'latitude', screenname: '座標・緯度', category: category)
AnnotationAttribute.create!(name: 'longitude', screenname: '座標・経度', category: category)
AnnotationAttribute.create!(name: 'tourist_spot', screenname: '観光地', category: category)
AnnotationAttribute.create!(name: 'bridge_tunnel', screenname: '橋・トンネル', category: category)
AnnotationAttribute.create!(name: 'park', screenname: '公園', category: category)
AnnotationAttribute.create!(name: 'industry', screenname: '産業', category: category)
AnnotationAttribute.create!(name: 'animal', screenname: '動物', category: category)
AnnotationAttribute.create!(name: 'plant', screenname: '植物', category: category)
AnnotationAttribute.create!(name: 'origin', screenname: '成因', category: category)
AnnotationAttribute.create!(name: 'origin_of_name', screenname: '名前の謂れ', category: category)

category = Category.create!(name: 'mountain', screenname: '山地名', def_link: 'http://example.com')

# load attributes
# ---------------

AnnotationAttribute.create!(name: 'alias', screenname: '別名', category: category)
AnnotationAttribute.create!(name: 'kana', screenname: 'ふりがな', category: category)
AnnotationAttribute.create!(name: 'type', screenname: '種類', category: category)
AnnotationAttribute.create!(name: 'country', screenname: '国', category: category)
AnnotationAttribute.create!(name: 'domestic_position', screenname: '国内位置', category: category)
AnnotationAttribute.create!(name: 'location', screenname: '所在地', category: category)
AnnotationAttribute.create!(name: 'continental_region', screenname: '大陸地域', category: category)
AnnotationAttribute.create!(name: 'position_in_continental_region', screenname: '大陸地域内位置', category: category)
AnnotationAttribute.create!(name: 'belonging_mountain_range', screenname: '属する山系', category: category)
AnnotationAttribute.create!(name: 'constituent_mountain', screenname: '構成する山', category: category)
AnnotationAttribute.create!(name: 'nearby_mountain', screenname: '付近の山地名', category: category)
AnnotationAttribute.create!(name: 'highest_peak', screenname: '最高峰', category: category)
AnnotationAttribute.create!(name: 'river', screenname: '河川', category: category)
AnnotationAttribute.create!(name: 'lake', screenname: '湖沼', category: category)
AnnotationAttribute.create!(name: 'latitude', screenname: '座標・緯度', category: category)
AnnotationAttribute.create!(name: 'longitude', screenname: '座標・経度', category: category)
AnnotationAttribute.create!(name: 'length', screenname: '延長', category: category)
AnnotationAttribute.create!(name: 'width', screenname: '幅', category: category)
AnnotationAttribute.create!(name: 'elevation', screenname: '標高', category: category)
AnnotationAttribute.create!(name: 'origin_of_name', screenname: '名前の謂れ', category: category)
AnnotationAttribute.create!(name: 'park', screenname: '公園', category: category)
AnnotationAttribute.create!(name: 'animal', screenname: '動物', category: category)
AnnotationAttribute.create!(name: 'plant', screenname: '植物', category: category)
AnnotationAttribute.create!(name: 'tourist_spot', screenname: '観光地', category: category)
AnnotationAttribute.create!(name: 'industry', screenname: '産業', category: category)
AnnotationAttribute.create!(name: 'rock_composition', screenname: '含有岩石', category: category)
AnnotationAttribute.create!(name: 'holy_spirit', screenname: '神霊', category: category)
AnnotationAttribute.create!(name: 'name_of_first_ascent', screenname: '初登頂者名・登山隊名', category: category)
AnnotationAttribute.create!(name: 'first_ascent_year', screenname: '初登頂年', category: category)
AnnotationAttribute.create!(name: 'nationality_of_first_ascent', screenname: '初登頂者国籍', category: category)
AnnotationAttribute.create!(name: 'name_of_ascent_person', screenname: '登頂者', category: category)
AnnotationAttribute.create!(name: 'nationality_of_ascent_person', screenname: '登頂者の国籍', category: category)
AnnotationAttribute.create!(name: 'expedition', screenname: '登山隊', category: category)
AnnotationAttribute.create!(name: 'nationality_of_expedition', screenname: '登山隊の国籍', category: category)

category = Category.create!(name: 'river', screenname: '河川名', def_link: 'http://example.com')

# load attributes
# ---------------

AnnotationAttribute.create!(name: 'kana', screenname: 'ふりがな', category: category)
AnnotationAttribute.create!(name: 'alias', screenname: '別名', category: category)
AnnotationAttribute.create!(name: 'country', screenname: '国', category: category)
AnnotationAttribute.create!(name: 'domestic_position', screenname: '国内位置', category: category)
AnnotationAttribute.create!(name: 'location', screenname: '所在地', category: category)
AnnotationAttribute.create!(name: 'inflow_source', screenname: '流入元', category: category)
AnnotationAttribute.create!(name: 'water_source', screenname: '水源', category: category)
AnnotationAttribute.create!(name: 'inflow_and_confluence_destination', screenname: '流入・合流先', category: category)
AnnotationAttribute.create!(name: 'area_of_basin', screenname: '流域面積', category: category)
AnnotationAttribute.create!(name: 'length', screenname: '長さ', category: category)
AnnotationAttribute.create!(name: 'average_flow', screenname: '平均流量', category: category)
AnnotationAttribute.create!(name: 'elevation_of_water_source', screenname: '水源の標高', category: category)
AnnotationAttribute.create!(name: 'origin_of_name', screenname: '名前の謂れ', category: category)
AnnotationAttribute.create!(name: 'animal', screenname: '動物', category: category)
AnnotationAttribute.create!(name: 'tourist_spot', screenname: '観光地', category: category)
AnnotationAttribute.create!(name: 'dam', screenname: 'ダム', category: category)
AnnotationAttribute.create!(name: 'bridge_tunnel', screenname: '橋・トンネル', category: category)

category = Category.create!(name: 'sea', screenname: '海洋名', def_link: 'http://example.com')

# load attributes
# ---------------

AnnotationAttribute.create!(name: 'kana', screenname: 'ふりがな', category: category)
AnnotationAttribute.create!(name: 'alias', screenname: '別名', category: category)
AnnotationAttribute.create!(name: 'type', screenname: '種類', category: category)
AnnotationAttribute.create!(name: 'country', screenname: '国', category: category)
AnnotationAttribute.create!(name: 'location', screenname: '所在地', category: category)
AnnotationAttribute.create!(name: 'coastal_region', screenname: '沿岸地域区分', category: category)
AnnotationAttribute.create!(name: 'belonging_sea_area', screenname: '属する海域', category: category)
AnnotationAttribute.create!(name: 'constituent_sea_are', screenname: '構成する海域', category: category)
AnnotationAttribute.create!(name: 'river', screenname: '河川', category: category)
AnnotationAttribute.create!(name: 'island', screenname: '島', category: category)
AnnotationAttribute.create!(name: 'coast', screenname: '海岸', category: category)
AnnotationAttribute.create!(name: 'formation_time', screenname: '形成時期', category: category)
AnnotationAttribute.create!(name: 'water_depth', screenname: '水深', category: category)
AnnotationAttribute.create!(name: 'average_depth', screenname: '平均水深', category: category)
AnnotationAttribute.create!(name: 'maximum_depth', screenname: '最大水深', category: category)
AnnotationAttribute.create!(name: 'area', screenname: '表面積', category: category)
AnnotationAttribute.create!(name: 'length', screenname: '長さ', category: category)
AnnotationAttribute.create!(name: 'width', screenname: '幅', category: category)
AnnotationAttribute.create!(name: 'speed_of_flow', screenname: '流速', category: category)
AnnotationAttribute.create!(name: 'latitude', screenname: '座標・緯度', category: category)
AnnotationAttribute.create!(name: 'longitude', screenname: '座標・経度', category: category)
AnnotationAttribute.create!(name: 'tourist_spot', screenname: '観光地', category: category)
AnnotationAttribute.create!(name: 'harbor', screenname: '港', category: category)
AnnotationAttribute.create!(name: 'bridge_tunnel', screenname: '橋・トンネル', category: category)
AnnotationAttribute.create!(name: 'park', screenname: '公園', category: category)
AnnotationAttribute.create!(name: 'industry', screenname: '産業', category: category)
AnnotationAttribute.create!(name: 'animal', screenname: '動物', category: category)
AnnotationAttribute.create!(name: 'origin_of_name', screenname: '名前の謂れ', category: category)

category = Category.create!(name: 'spa', screenname: '温泉名', def_link: 'http://example.com')

# load attributes
# ---------------

AnnotationAttribute.create!(name: 'alias', screenname: '別名', category: category)
AnnotationAttribute.create!(name: 'kana', screenname: 'ふりがな', category: category)
AnnotationAttribute.create!(name: 'country', screenname: '国名', category: category)
AnnotationAttribute.create!(name: 'domestic_position', screenname: '国内位置', category: category)
AnnotationAttribute.create!(name: 'location', screenname: '所在地', category: category)
AnnotationAttribute.create!(name: 'belonging_spa', screenname: '属する温泉郷', category: category)
AnnotationAttribute.create!(name: 'constituent_spa', screenname: '構成する温泉', category: category)
AnnotationAttribute.create!(name: 'nearby_river', screenname: '付近の河川', category: category)
AnnotationAttribute.create!(name: 'open_year', screenname: '開湯年', category: category)
AnnotationAttribute.create!(name: 'source_name', screenname: '源泉名', category: category)
AnnotationAttribute.create!(name: 'latitude', screenname: '座標・緯度', category: category)
AnnotationAttribute.create!(name: 'longitude', screenname: '座標・経度', category: category)
AnnotationAttribute.create!(name: 'spring_quality', screenname: '泉質', category: category)
AnnotationAttribute.create!(name: 'quality', screenname: '液性', category: category)
AnnotationAttribute.create!(name: 'ph', screenname: 'pH', category: category)
AnnotationAttribute.create!(name: 'temperature', screenname: '泉温', category: category)
AnnotationAttribute.create!(name: 'output', screenname: '湧出量', category: category)
AnnotationAttribute.create!(name: 'tourist_spot', screenname: '観光地', category: category)
AnnotationAttribute.create!(name: 'monument', screenname: '記念碑', category: category)
AnnotationAttribute.create!(name: 'nearest_station', screenname: '最寄駅', category: category)
AnnotationAttribute.create!(name: 'nearest_line', screenname: '最寄路線', category: category)
AnnotationAttribute.create!(name: 'origin_of_name', screenname: '名前の謂れ', category: category)

# Merge Tasks & Link Tasks
# ------------------------

lake = Category.find_by(name: 'lake')
page = Page.create!(aid: 1, pageid: 1234, title: 'test', category: lake)
p = Paragraph.create!(page: page, body: "<p>バルハシ湖（カザフ語: Balqash Köli、ロシア語: Озеро Балхаш）は、カザフスタン東部にある湖。中央アジア最大の湖である（カスピ海は西アジアとヨーロッパと境にあり、中央アジアの湖ではない）[要出典]。</p>", no_tag: "バルハシ湖（カザフ語: Balqash Köli、ロシア語: Озеро Балхаш）は、カザフスタン東部にある湖。中央アジア最大の湖である（カスピ海は西アジアとヨーロッパと境にあり、中央アジアの湖ではない）[要出典]。")

mtask = MergeTask.create!(page: page)
lt = LinkTask.create!(page: page)

ma = MergeAttribute.create!(merge_task: mtask, name: "country", screenname: "国")
mv = MergeValue.create!(merge_attribute: ma, value: "カザフスタン")
mt = MergeTag.create!(merge_value: mv, paragraph: p, start_offset: 46, end_offset: 52, status: :approved)
la = LinkAnnotation.create!(link_task: lt, merge_tag: mt)
EntityLink.create!(link_annotation: la, title: "カザフスタン", pageid: 8599,
                  first_sentence: "カザフスタン共和国（カザフスタンきょうわこく、カザフ語: Қазақстан Республикасы）、通称カザフスタンは、中央アジアの共和制国家である。")
EntityLink.create!(link_annotation: la, title: "カザフスタン料理", pageid: 8599,
                  first_sentence: "カザフスタン料理 (カザフスタンりょうり) はカザフスタンで食されている料理である。")

ma = MergeAttribute.create!(merge_task: mtask, name: "kana", screenname: "読み")
mv = MergeValue.create!(merge_attribute: ma, value: "カザフスタン")
mt = MergeTag.create!(merge_value: mv, paragraph: p, start_offset: 46, end_offset: 52, status: :approved)
la = LinkAnnotation.create!(link_task: lt, merge_tag: mt)
EntityLink.create!(link_annotation: la, title: "カザフスタン", pageid: 8599,
                  first_sentence: "カザフスタン共和国（カザフスタンきょうわこく、カザフ語: Қазақстан Республикасы）、通称カザフスタンは、中央アジアの共和制国家である。")

ma = MergeAttribute.create!(merge_task: mtask, name: "country", screenname: "国")
mv = MergeValue.create!(merge_attribute: ma, value: "カザフ")
mt = MergeTag.create!(merge_value: mv, paragraph: p, start_offset: 46, end_offset: 49, status: :approved)
la = LinkAnnotation.create!(link_task: lt, merge_tag: mt)
EntityLink.create!(link_annotation: la, title: "カザフスタン", pageid: 8599,
                  first_sentence: "カザフスタン共和国（カザフスタンきょうわこく、カザフ語: Қазақстан Республикасы）、通称カザフスタンは、中央アジアの共和制国家である。")

ma = MergeAttribute.create!(merge_task: mtask, name: "kana", screenname: "読み")
mv = MergeValue.create!(merge_attribute: ma, value: "スタン")
mt = MergeTag.create!(merge_value: mv, paragraph: p, start_offset: 49, end_offset: 52, status: :approved)
la = LinkAnnotation.create!(link_task: lt, merge_tag: mt)
EntityLink.create!(link_annotation: la, title: "カザフスタン", pageid: 8599,
                  first_sentence: "カザフスタン共和国（カザフスタンきょうわこく、カザフ語: Қазақстан Республикасы）、通称カザフスタンは、中央アジアの共和制国家である。")

ma = MergeAttribute.create!(merge_task: mtask, name: "type", screenname: "種類")
mv = MergeValue.create!(merge_attribute: ma, value: "湖")
mt = MergeTag.create!(merge_value: mv, paragraph: p, start_offset: 57, end_offset: 58, status: :approved)
la = LinkAnnotation.create!(link_task: lt, merge_tag: mt)
EntityLink.create!(link_annotation: la, title: "湖", pageid: 1431634)
